name: Caddy

on:
  push:
    branches:
      - main
    paths:
      - 'caddy/**'
      - '.github/workflows/caddy.yml'
  pull_request:
    branches:
      - main

jobs:
  caddy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push caddy images to latest
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPO_CADDY }}
        tags: latest
        push: ${{ startsWith(github.ref, 'refs/heads/main') }}
        path: ./caddy
